import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialMigrations1707638538731 implements MigrationInterface {
    name = 'InitialMigrations1707638538731'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "permission" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "code_name" character varying(30) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_1c72a9891f3423e4433f1442abd" UNIQUE ("code_name"), CONSTRAINT "PK_3b8b97af9d9d8807e41e6f48362" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "role" ("id" SERIAL NOT NULL, "name" character varying(20) NOT NULL, "description" character varying(100), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ae4578dcaed5adff96595e61660" UNIQUE ("name"), CONSTRAINT "PK_b36bcfe02fc8de3c57a8b2391c2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_gender_enum" AS ENUM('MALE', 'FEMALE', 'OTHER')`);
        await queryRunner.query(`CREATE TABLE "user" ("id" SERIAL NOT NULL, "name" character varying(50) NOT NULL, "email" character varying(30) NOT NULL, "phone_number" character varying(13) NOT NULL, "gender" "public"."user_gender_enum" NOT NULL DEFAULT 'OTHER', "password" character varying NOT NULL, "status" boolean NOT NULL DEFAULT true, "last_login" TIMESTAMP, "refresh_token" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email"), CONSTRAINT "UQ_01eea41349b6c9275aec646eee0" UNIQUE ("phone_number"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."notification_notification_type_enum" AS ENUM('ACTION', 'CRITICAL', 'WARN', 'INFO')`);
        await queryRunner.query(`CREATE TABLE "notification" ("id" SERIAL NOT NULL, "message" character varying NOT NULL, "read" boolean NOT NULL DEFAULT false, "notification_type" "public"."notification_notification_type_enum" NOT NULL DEFAULT 'INFO', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "recipientId" integer, CONSTRAINT "PK_705b6c7cdf9b2c2ff7ac7872cb7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ab7cbe7a013ecac5da0a8f8888" ON "notification" ("recipientId") `);
        await queryRunner.query(`CREATE TABLE "menu" ("id" SERIAL NOT NULL, "item" character varying(100) NOT NULL, "item_local_name" character varying(100), "description" character varying(100), "price" numeric(10,2) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_fcf4d7206505dc2cc0ed78fc8ae" UNIQUE ("item"), CONSTRAINT "PK_35b2a8f47d153ff7a41860cceeb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_item" ON "menu" ("item") `);
        await queryRunner.query(`CREATE TYPE "public"."staff_staff_type_enum" AS ENUM('WAITER')`);
        await queryRunner.query(`CREATE TABLE "staff" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "phone_number" character varying(13) NOT NULL, "staff_type" "public"."staff_staff_type_enum" NOT NULL, "status" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_26bf58093d6c520b6fe572dc091" UNIQUE ("phone_number"), CONSTRAINT "PK_e4ee98bb552756c180aec1e854a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "facility_type" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "description" character varying(200), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_903841da08f30fad8c084a3fe5c" UNIQUE ("name"), CONSTRAINT "PK_426a0e9724bbd5313fc99c46518" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "supplier" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "email" character varying(30), "phone_number" character varying(13) NOT NULL, "address" character varying(100), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_c40cbff7400f06ae1c8d9f42333" UNIQUE ("email"), CONSTRAINT "UQ_c4854ccf3a0c9d5ac7930e029ba" UNIQUE ("phone_number"), CONSTRAINT "PK_2bc0d2cab6276144d2ff98a2828" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."room_room_type_enum" AS ENUM('BED', 'MEETING_HALL')`);
        await queryRunner.query(`CREATE TABLE "room" ("id" SERIAL NOT NULL, "name" character varying(10) NOT NULL, "price" integer NOT NULL, "room_type" "public"."room_room_type_enum" NOT NULL, "notes" character varying, "available" boolean NOT NULL DEFAULT true, "status" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_535c742a3606d2e3122f441b26c" UNIQUE ("name"), CONSTRAINT "PK_c6d46db005d623e691b2fbcba23" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."work_flow_flow_type_enum" AS ENUM('PURCHASE_ORDER', 'PURCHASE_RECEIVABLE', 'STORE_REQUISITION')`);
        await queryRunner.query(`CREATE TYPE "public"."work_flow_step_enum" AS ENUM('REQUEST', 'CHECK', 'APPROVE', 'RELEASE')`);
        await queryRunner.query(`CREATE TABLE "work_flow" ("id" SERIAL NOT NULL, "flow_type" "public"."work_flow_flow_type_enum" NOT NULL, "step" "public"."work_flow_step_enum" NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_53c5b5fa1f4ac75c6c200d7cb6e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "category" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "description" character varying(200), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_23c05c292c439d77b0de816b500" UNIQUE ("name"), CONSTRAINT "PK_9c4e4a89e3674fc9f382d733f03" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."product_unit_of_measure_enum" AS ENUM('Each', 'Dozen', 'Piece', 'Pack', 'Set', 'Case', 'Bag', 'Box', 'Carton', 'Pallet', 'Roll', 'Bundle', 'Gross', 'Net', 'Liter', 'Milliliter', 'Gallon', 'Quart', 'Pint', 'Ounce', 'Pound', 'Gram', 'Kilogram', 'Ton', 'Square Meter', 'Square Foot', 'Cubic Meter', 'Cubic Foot', 'Inch', 'Foot', 'Meter', 'Centimeter', 'Millimeter', 'Yard', 'Milligram', 'Gigagram', 'Barrel', 'Drum', 'Crate', 'Bin', 'Rack', 'Tote', 'Ream', 'Sheet', 'Pail', 'Gallon (US)', 'Gallon (UK)', 'Bushel', 'Bale', 'Unit', 'Other')`);
        await queryRunner.query(`CREATE TABLE "product" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "unit_of_measure" "public"."product_unit_of_measure_enum" NOT NULL DEFAULT 'Piece', "notes" character varying(200), "safety_stock_level" integer, "stock_quantity" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "categoryId" integer, CONSTRAINT "UQ_22cc43e9a74d7498546e9a63e77" UNIQUE ("name"), CONSTRAINT "PK_bebc9158e480b949565b4dc7a82" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order_item" ("id" SERIAL NOT NULL, "quantity" integer NOT NULL, "remark" character varying, "orderId" integer, "productId" integer, CONSTRAINT "PK_d01158fe15b1ead5c26fd7f4e90" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."order_status_enum" AS ENUM('Requested', 'Checked', 'Approved', 'Rejected')`);
        await queryRunner.query(`CREATE TABLE "order" ("id" SERIAL NOT NULL, "order_number" character varying(20) NOT NULL, "order_date" TIMESTAMP NOT NULL, "status" "public"."order_status_enum" NOT NULL DEFAULT 'Requested', "rejection_reason" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "requestedById" integer, "checkedById" integer, "approvedById" integer, "rejectedById" integer, CONSTRAINT "UQ_f9180f384353c621e8d0c414c14" UNIQUE ("order_number"), CONSTRAINT "PK_1031171c13130102495201e3e20" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."receivable_status_enum" AS ENUM('Requested', 'Received', 'Rejected')`);
        await queryRunner.query(`CREATE TABLE "receivable" ("id" SERIAL NOT NULL, "receivable_number" character varying(20) NOT NULL, "receivable_date" TIMESTAMP NOT NULL, "status" "public"."receivable_status_enum" NOT NULL DEFAULT 'Requested', "rejection_reason" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "orderId" integer, "preparedById" integer, "receivedById" integer, "rejectedById" integer, "supplierId" integer, CONSTRAINT "UQ_28b48290cbafa4950272b72718c" UNIQUE ("receivable_number"), CONSTRAINT "REL_eeb2dc1e123dda0e308ed9461f" UNIQUE ("orderId"), CONSTRAINT "PK_21914351fc68743079856ee3b1f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "receivable_item" ("id" SERIAL NOT NULL, "quantity" integer NOT NULL, "unit_price" integer NOT NULL, "total_price" integer NOT NULL, "remark" character varying, "receivableId" integer, "productId" integer, CONSTRAINT "PK_e3adfe28ac25c48faef8d723e70" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "book_room" ("id" SERIAL NOT NULL, "book_date" TIMESTAMP NOT NULL DEFAULT now(), "notes" character varying, "guest_in" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "roomId" integer, "operatorId" integer, CONSTRAINT "PK_6efabb86c5fb68b9bb2e4ce66b1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cash_receipt_item" ("id" SERIAL NOT NULL, "quantity" integer NOT NULL, "unit_price" numeric NOT NULL, "total_price" numeric NOT NULL, "cashReceiptId" integer, "menuId" integer, CONSTRAINT "PK_beb48b0925d695e0243fed2e768" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."cash_receipt_status_enum" AS ENUM('PENDING', 'PRINTED')`);
        await queryRunner.query(`CREATE TABLE "cash_receipt" ("id" SERIAL NOT NULL, "cash_receipt_number" character varying(20) NOT NULL, "cash_receipt_date" TIMESTAMP NOT NULL, "status" "public"."cash_receipt_status_enum" NOT NULL DEFAULT 'PENDING', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "casherId" integer, "waiterId" integer, CONSTRAINT "UQ_9a2344e1b9c983a11829d9e4dd1" UNIQUE ("cash_receipt_number"), CONSTRAINT "PK_0fd8a136b9e27f6f65e50b19c07" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."captain_order_status_enum" AS ENUM('PENDING', 'PRINTED', 'PAID')`);
        await queryRunner.query(`CREATE TABLE "captain_order" ("id" SERIAL NOT NULL, "captain_order_number" character varying(20) NOT NULL, "captain_order_date" TIMESTAMP NOT NULL, "status" "public"."captain_order_status_enum" NOT NULL DEFAULT 'PENDING', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "createdById" integer, "waiterId" integer, "facilityTypeId" integer, "cashReceiptId" integer, CONSTRAINT "UQ_821b6e7dab1ef4ea9eee232119c" UNIQUE ("captain_order_number"), CONSTRAINT "PK_4df764c09edbc24f4abcf974856" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "captain_order_item" ("id" SERIAL NOT NULL, "quantity" integer NOT NULL, "captainOrderId" integer, "menuId" integer, CONSTRAINT "PK_270cfa9b6ab38f5a871fd1da0c7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."store_requisition_status_enum" AS ENUM('Requested', 'Approved', 'Rejected', 'Released')`);
        await queryRunner.query(`CREATE TABLE "store_requisition" ("id" SERIAL NOT NULL, "store_requisition_number" character varying(20) NOT NULL, "store_requisition_date" TIMESTAMP NOT NULL, "status" "public"."store_requisition_status_enum" NOT NULL DEFAULT 'Requested', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "requestedById" integer, "approvedById" integer, "releasedById" integer, CONSTRAINT "UQ_97d7bcbe0de53de4856e8d3aa99" UNIQUE ("store_requisition_number"), CONSTRAINT "PK_64585df9569216319b20069d66c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "store_requisition_item" ("id" SERIAL NOT NULL, "quantity" integer NOT NULL, "remark" character varying, "storeRequisitionId" integer, "productId" integer, CONSTRAINT "PK_6b623b29ed1e966c351873c2ff4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("role_id" integer NOT NULL, "permission_id" integer NOT NULL, CONSTRAINT "PK_25d24010f53bb80b78e412c9656" PRIMARY KEY ("role_id", "permission_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_178199805b901ccd220ab7740e" ON "role_permissions" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_17022daf3f885f7d35423e9971" ON "role_permissions" ("permission_id") `);
        await queryRunner.query(`CREATE TABLE "user_roles" ("user_id" integer NOT NULL, "role_id" integer NOT NULL, CONSTRAINT "PK_23ed6f04fe43066df08379fd034" PRIMARY KEY ("user_id", "role_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_87b8888186ca9769c960e92687" ON "user_roles" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b23c65e50a758245a33ee35fda" ON "user_roles" ("role_id") `);
        await queryRunner.query(`CREATE TABLE "facility_type_roles" ("facility_type_id" integer NOT NULL, "role_id" integer NOT NULL, CONSTRAINT "PK_b84cb32860fb6d37dd0a418c3e5" PRIMARY KEY ("facility_type_id", "role_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e80daa4b42eca442acc9aea9c4" ON "facility_type_roles" ("facility_type_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_40cfa85ee3992cae665ecfd8dc" ON "facility_type_roles" ("role_id") `);
        await queryRunner.query(`CREATE TABLE "workflow_notify_to" ("work_flow_id" integer NOT NULL, "role_id" integer NOT NULL, CONSTRAINT "PK_516cb41a2195343e2e55c3cb669" PRIMARY KEY ("work_flow_id", "role_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fa6f2a95cadede85f03503cb81" ON "workflow_notify_to" ("work_flow_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3e652c6ef972b4e9d02522496f" ON "workflow_notify_to" ("role_id") `);
        await queryRunner.query(`ALTER TABLE "notification" ADD CONSTRAINT "FK_ab7cbe7a013ecac5da0a8f88884" FOREIGN KEY ("recipientId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "FK_ff0c0301a95e517153df97f6812" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD CONSTRAINT "FK_646bf9ece6f45dbe41c203e06e0" FOREIGN KEY ("orderId") REFERENCES "order"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD CONSTRAINT "FK_904370c093ceea4369659a3c810" FOREIGN KEY ("productId") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_168be56760bc2b4304afa40c276" FOREIGN KEY ("requestedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_156d0373e834ca6e63f775ddbe1" FOREIGN KEY ("checkedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_4e982044d3432e6630340ad8b2a" FOREIGN KEY ("approvedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_c9d9fb4f0b7d9285395459240ce" FOREIGN KEY ("rejectedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "receivable" ADD CONSTRAINT "FK_eeb2dc1e123dda0e308ed9461f5" FOREIGN KEY ("orderId") REFERENCES "order"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "receivable" ADD CONSTRAINT "FK_a7ed71845bd88dd955e3e5b01c5" FOREIGN KEY ("preparedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "receivable" ADD CONSTRAINT "FK_223e1e62f03be936bbdb6dff970" FOREIGN KEY ("receivedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "receivable" ADD CONSTRAINT "FK_31b0daa69b2575ade1e3f800f1f" FOREIGN KEY ("rejectedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "receivable" ADD CONSTRAINT "FK_48b5756e46e45349f12a7db09d5" FOREIGN KEY ("supplierId") REFERENCES "supplier"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "receivable_item" ADD CONSTRAINT "FK_c122a7217d4c307da24e8aa98b2" FOREIGN KEY ("receivableId") REFERENCES "receivable"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "receivable_item" ADD CONSTRAINT "FK_74cc224ed59eb0d408b2817e91a" FOREIGN KEY ("productId") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "book_room" ADD CONSTRAINT "FK_9b9081964118a30e5024d1ba8fb" FOREIGN KEY ("roomId") REFERENCES "room"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "book_room" ADD CONSTRAINT "FK_7f79820d10762b02fa6d252c3b2" FOREIGN KEY ("operatorId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cash_receipt_item" ADD CONSTRAINT "FK_93fdd1769c84fdc36857d9aab89" FOREIGN KEY ("cashReceiptId") REFERENCES "cash_receipt"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cash_receipt_item" ADD CONSTRAINT "FK_1a5b582dab8cb61b3e6f3ef11a9" FOREIGN KEY ("menuId") REFERENCES "menu"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cash_receipt" ADD CONSTRAINT "FK_c4451f5508f657b0d27b968e055" FOREIGN KEY ("casherId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cash_receipt" ADD CONSTRAINT "FK_7a32563ede632ea46156fd6d176" FOREIGN KEY ("waiterId") REFERENCES "staff"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "captain_order" ADD CONSTRAINT "FK_33b570e787f40f3635a34fe3a6b" FOREIGN KEY ("createdById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "captain_order" ADD CONSTRAINT "FK_db99c91a055c0107acb3850f28e" FOREIGN KEY ("waiterId") REFERENCES "staff"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "captain_order" ADD CONSTRAINT "FK_ca25baf263dc7a635981f5ed48a" FOREIGN KEY ("facilityTypeId") REFERENCES "facility_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "captain_order" ADD CONSTRAINT "FK_c60deb4992fdbeb79a2a87978b3" FOREIGN KEY ("cashReceiptId") REFERENCES "cash_receipt"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "captain_order_item" ADD CONSTRAINT "FK_df41f11222a470df49a073cb97e" FOREIGN KEY ("captainOrderId") REFERENCES "captain_order"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "captain_order_item" ADD CONSTRAINT "FK_3e463297853fabb44d4ea127637" FOREIGN KEY ("menuId") REFERENCES "menu"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "store_requisition" ADD CONSTRAINT "FK_1db95ef821a7d52a491fd8ee421" FOREIGN KEY ("requestedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "store_requisition" ADD CONSTRAINT "FK_ba40f526b8378ce4c2850db7acb" FOREIGN KEY ("approvedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "store_requisition" ADD CONSTRAINT "FK_2d665f301419bdcbfbccfa24037" FOREIGN KEY ("releasedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "store_requisition_item" ADD CONSTRAINT "FK_d6e0f9f1a51d77df208899d50ae" FOREIGN KEY ("storeRequisitionId") REFERENCES "store_requisition"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "store_requisition_item" ADD CONSTRAINT "FK_7eefcedd7ef8c0f1953956dbbcb" FOREIGN KEY ("productId") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "role"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permission"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_87b8888186ca9769c960e926870" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_b23c65e50a758245a33ee35fda1" FOREIGN KEY ("role_id") REFERENCES "role"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "facility_type_roles" ADD CONSTRAINT "FK_e80daa4b42eca442acc9aea9c41" FOREIGN KEY ("facility_type_id") REFERENCES "facility_type"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "facility_type_roles" ADD CONSTRAINT "FK_40cfa85ee3992cae665ecfd8dc4" FOREIGN KEY ("role_id") REFERENCES "role"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "workflow_notify_to" ADD CONSTRAINT "FK_fa6f2a95cadede85f03503cb81a" FOREIGN KEY ("work_flow_id") REFERENCES "work_flow"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "workflow_notify_to" ADD CONSTRAINT "FK_3e652c6ef972b4e9d02522496fc" FOREIGN KEY ("role_id") REFERENCES "role"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "workflow_notify_to" DROP CONSTRAINT "FK_3e652c6ef972b4e9d02522496fc"`);
        await queryRunner.query(`ALTER TABLE "workflow_notify_to" DROP CONSTRAINT "FK_fa6f2a95cadede85f03503cb81a"`);
        await queryRunner.query(`ALTER TABLE "facility_type_roles" DROP CONSTRAINT "FK_40cfa85ee3992cae665ecfd8dc4"`);
        await queryRunner.query(`ALTER TABLE "facility_type_roles" DROP CONSTRAINT "FK_e80daa4b42eca442acc9aea9c41"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_b23c65e50a758245a33ee35fda1"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_87b8888186ca9769c960e926870"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "store_requisition_item" DROP CONSTRAINT "FK_7eefcedd7ef8c0f1953956dbbcb"`);
        await queryRunner.query(`ALTER TABLE "store_requisition_item" DROP CONSTRAINT "FK_d6e0f9f1a51d77df208899d50ae"`);
        await queryRunner.query(`ALTER TABLE "store_requisition" DROP CONSTRAINT "FK_2d665f301419bdcbfbccfa24037"`);
        await queryRunner.query(`ALTER TABLE "store_requisition" DROP CONSTRAINT "FK_ba40f526b8378ce4c2850db7acb"`);
        await queryRunner.query(`ALTER TABLE "store_requisition" DROP CONSTRAINT "FK_1db95ef821a7d52a491fd8ee421"`);
        await queryRunner.query(`ALTER TABLE "captain_order_item" DROP CONSTRAINT "FK_3e463297853fabb44d4ea127637"`);
        await queryRunner.query(`ALTER TABLE "captain_order_item" DROP CONSTRAINT "FK_df41f11222a470df49a073cb97e"`);
        await queryRunner.query(`ALTER TABLE "captain_order" DROP CONSTRAINT "FK_c60deb4992fdbeb79a2a87978b3"`);
        await queryRunner.query(`ALTER TABLE "captain_order" DROP CONSTRAINT "FK_ca25baf263dc7a635981f5ed48a"`);
        await queryRunner.query(`ALTER TABLE "captain_order" DROP CONSTRAINT "FK_db99c91a055c0107acb3850f28e"`);
        await queryRunner.query(`ALTER TABLE "captain_order" DROP CONSTRAINT "FK_33b570e787f40f3635a34fe3a6b"`);
        await queryRunner.query(`ALTER TABLE "cash_receipt" DROP CONSTRAINT "FK_7a32563ede632ea46156fd6d176"`);
        await queryRunner.query(`ALTER TABLE "cash_receipt" DROP CONSTRAINT "FK_c4451f5508f657b0d27b968e055"`);
        await queryRunner.query(`ALTER TABLE "cash_receipt_item" DROP CONSTRAINT "FK_1a5b582dab8cb61b3e6f3ef11a9"`);
        await queryRunner.query(`ALTER TABLE "cash_receipt_item" DROP CONSTRAINT "FK_93fdd1769c84fdc36857d9aab89"`);
        await queryRunner.query(`ALTER TABLE "book_room" DROP CONSTRAINT "FK_7f79820d10762b02fa6d252c3b2"`);
        await queryRunner.query(`ALTER TABLE "book_room" DROP CONSTRAINT "FK_9b9081964118a30e5024d1ba8fb"`);
        await queryRunner.query(`ALTER TABLE "receivable_item" DROP CONSTRAINT "FK_74cc224ed59eb0d408b2817e91a"`);
        await queryRunner.query(`ALTER TABLE "receivable_item" DROP CONSTRAINT "FK_c122a7217d4c307da24e8aa98b2"`);
        await queryRunner.query(`ALTER TABLE "receivable" DROP CONSTRAINT "FK_48b5756e46e45349f12a7db09d5"`);
        await queryRunner.query(`ALTER TABLE "receivable" DROP CONSTRAINT "FK_31b0daa69b2575ade1e3f800f1f"`);
        await queryRunner.query(`ALTER TABLE "receivable" DROP CONSTRAINT "FK_223e1e62f03be936bbdb6dff970"`);
        await queryRunner.query(`ALTER TABLE "receivable" DROP CONSTRAINT "FK_a7ed71845bd88dd955e3e5b01c5"`);
        await queryRunner.query(`ALTER TABLE "receivable" DROP CONSTRAINT "FK_eeb2dc1e123dda0e308ed9461f5"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_c9d9fb4f0b7d9285395459240ce"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_4e982044d3432e6630340ad8b2a"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_156d0373e834ca6e63f775ddbe1"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_168be56760bc2b4304afa40c276"`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP CONSTRAINT "FK_904370c093ceea4369659a3c810"`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP CONSTRAINT "FK_646bf9ece6f45dbe41c203e06e0"`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "FK_ff0c0301a95e517153df97f6812"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP CONSTRAINT "FK_ab7cbe7a013ecac5da0a8f88884"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3e652c6ef972b4e9d02522496f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fa6f2a95cadede85f03503cb81"`);
        await queryRunner.query(`DROP TABLE "workflow_notify_to"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_40cfa85ee3992cae665ecfd8dc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e80daa4b42eca442acc9aea9c4"`);
        await queryRunner.query(`DROP TABLE "facility_type_roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b23c65e50a758245a33ee35fda"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87b8888186ca9769c960e92687"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17022daf3f885f7d35423e9971"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_178199805b901ccd220ab7740e"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP TABLE "store_requisition_item"`);
        await queryRunner.query(`DROP TABLE "store_requisition"`);
        await queryRunner.query(`DROP TYPE "public"."store_requisition_status_enum"`);
        await queryRunner.query(`DROP TABLE "captain_order_item"`);
        await queryRunner.query(`DROP TABLE "captain_order"`);
        await queryRunner.query(`DROP TYPE "public"."captain_order_status_enum"`);
        await queryRunner.query(`DROP TABLE "cash_receipt"`);
        await queryRunner.query(`DROP TYPE "public"."cash_receipt_status_enum"`);
        await queryRunner.query(`DROP TABLE "cash_receipt_item"`);
        await queryRunner.query(`DROP TABLE "book_room"`);
        await queryRunner.query(`DROP TABLE "receivable_item"`);
        await queryRunner.query(`DROP TABLE "receivable"`);
        await queryRunner.query(`DROP TYPE "public"."receivable_status_enum"`);
        await queryRunner.query(`DROP TABLE "order"`);
        await queryRunner.query(`DROP TYPE "public"."order_status_enum"`);
        await queryRunner.query(`DROP TABLE "order_item"`);
        await queryRunner.query(`DROP TABLE "product"`);
        await queryRunner.query(`DROP TYPE "public"."product_unit_of_measure_enum"`);
        await queryRunner.query(`DROP TABLE "category"`);
        await queryRunner.query(`DROP TABLE "work_flow"`);
        await queryRunner.query(`DROP TYPE "public"."work_flow_step_enum"`);
        await queryRunner.query(`DROP TYPE "public"."work_flow_flow_type_enum"`);
        await queryRunner.query(`DROP TABLE "room"`);
        await queryRunner.query(`DROP TYPE "public"."room_room_type_enum"`);
        await queryRunner.query(`DROP TABLE "supplier"`);
        await queryRunner.query(`DROP TABLE "facility_type"`);
        await queryRunner.query(`DROP TABLE "staff"`);
        await queryRunner.query(`DROP TYPE "public"."staff_staff_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_item"`);
        await queryRunner.query(`DROP TABLE "menu"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ab7cbe7a013ecac5da0a8f8888"`);
        await queryRunner.query(`DROP TABLE "notification"`);
        await queryRunner.query(`DROP TYPE "public"."notification_notification_type_enum"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TYPE "public"."user_gender_enum"`);
        await queryRunner.query(`DROP TABLE "role"`);
        await queryRunner.query(`DROP TABLE "permission"`);
    }

}
